version: '3.8'

services:
  express:
    build:
      context: .
      dockerfile: ./server/Dockerfile.express
    ports:
      - "4132:4132"
    restart: always
    depends_on:
      - pocketbase
    environment:
      - APP_ENV=production
      - POCKETBASE_URL=http://pocketbase:4123

  pocketbase:
    build:
      context: .
      dockerfile: ./server/Dockerfile.pocketbase
    container_name: pocketbase
    ports:
      - "4133:4133"
    volumes:
      - pocketbase_data:/db/pb_data
    restart: always
